{
 "title": "Egg.js Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "stage",
    "label": "环境",
    "query": "label_values(egg_nodejs_version_info,stage)"
   },
   {
    "name": "appname",
    "label": "服务",
    "query": "label_values(egg_nodejs_version_info{stage=\"$stage\"},app)"
   },
   {
    "name": "node",
    "label": "主机",
    "query": "label_values(egg_nodejs_version_info{stage=\"$stage\",app=\"$appname\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "应用性能",
   "type": "gauge",
   "description": "满意值：小于 100ms，容忍值：100ms ~ 250ms。",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"100\"}[1h]))\n+\n  ((sum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"250\"}[1h])) - sum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"100\"}[1h]))) / 2)\n) / sum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[1h]))",
     "legendFormat": "worker"
    }
   ]
  },
  {
   "title": "请求总数",
   "type": "singlestat",
   "description": "应用当前机器启动后处理请求总数量",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(egg_http_request_total{stage=\"$stage\",app=\"$appname\",instance=\"$node\",worker=\"app\"}) by(worker)",
     "legendFormat": "1m平均值"
    }
   ]
  },
  {
   "title": "处理中请求数",
   "type": "singlestat",
   "description": "同一机器节点处理中还未响应的请求总数",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(egg_http_all_request_in_processing_total{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}) by(worker)"
    }
   ]
  },
  {
   "title": "分钟请求数",
   "type": "graph",
   "description": "同一机器节点平均每分钟请求量",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(egg_http_request_total{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}) by(worker)) - (sum(egg_http_request_total{stage=\"$stage\",app=\"$appname\",instance=\"$node\"} offset 1m) by(worker))"
    }
   ]
  },
  {
   "title": "进程存活周期",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "egg_nodejs_version_info{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}",
     "legendFormat": "{{worker}}-{{pid}}"
    }
   ]
  },
  {
   "title": "请求错误率",
   "type": "graph",
   "description": "500 错误请求占总请求数百分比。",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(irate(egg_http_all_errors_total{stage=\"$stage\",app=\"$appname\",instance=\"$node\",worker=\"app\"}[1m])) by(worker))\n/\n(sum(irate(egg_http_request_total{stage=\"$stage\",app=\"$appname\",instance=\"$node\",worker=\"app\"}[1m])) by(worker))) * 100"
    }
   ]
  },
  {
   "title": "常驻内存（rss）MB",
   "type": "graph",
   "description": "进程常驻内存",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "egg_process_resident_memory_bytes{stage=\"$stage\",app=\"$appname\",instance=\"$node\"} / 1024 / 1024",
     "legendFormat": "{{worker}}-{{pid}}"
    }
   ]
  },
  {
   "title": "响应时间占比",
   "type": "graph",
   "description": "5 分钟内平均响应时间占比",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"5\"}[5m]))\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "< 5ms (%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"10\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"5\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "5 ~ 10ms (%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"50\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"10\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "10 ~ 50ms (%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"100\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"50\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "50 ~ 100ms (%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"250\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"100\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "100 ~ 250ms (%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"500\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"250\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "250 ~ 500ms (%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"1000\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"500\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "500 ~ 1000ms(%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"10000\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"1000\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "1000 ~ 10000ms(%)"
    },
    {
     "expr": "((\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"+Inf\"}[5m]))\n-\nsum(irate(egg_http_request_duration_milliseconds_bucket{stage=\"$stage\",app=\"$appname\",instance=\"$node\",le=\"10000\"}[5m]))\n)\n/\nsum(irate(egg_http_request_duration_milliseconds_count{stage=\"$stage\",app=\"$appname\",instance=\"$node\"}[5m]))\n) * 100",
     "legendFormat": "> 10000ms or +Inf(%)"
    }
   ]
  },
  {
   "title": "外部内存（external）MB",
   "type": "graph",
   "description": "V8 管理的，绑定到 JavaScript 的 C++ 对象的内存使用情况",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "egg_nodejs_external_memory_bytes{stage=\"$stage\",app=\"$appname\",instance=\"$node\"} / 1024 / 1024",
     "legendFormat": "{{worker}}-{{pid}}"
    }
   ]
  },
  {
   "title": "堆内存（heapTotal & heapUsed）MB",
   "type": "graph",
   "description": "申请的堆内存，与已使用的堆内存。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "egg_nodejs_heap_size_total_bytes{stage=\"$stage\",app=\"$appname\",instance=\"$node\"} / 1024 / 1024",
     "legendFormat": "{{worker}}/{{pid}}"
    },
    {
     "expr": "egg_nodejs_heap_size_used_bytes{stage=\"$stage\",app=\"$appname\",instance=\"$node\"} / 1024 / 1024",
     "legendFormat": "{{worker}}/{{pid}}"
    }
   ]
  }
 ]
}